settings: {

  webHost: {
    domain: 'ci01.sc.pn',
    url: '',
    port: 80,

  },

  ciHelperService: {
    domain: 'ci01.sc.pn',
    url: '',
    port: 81,
     localDownloadDir: "C:/ci_downloads"
  },

  selenium: {
    webTimeout: 120,
    defaultWebDriver: !ruby/symbol firefox,
        max_retries: 12,
    sleep_time: 3,
  },

  reuseOldDeals: false,

   adminUsers: {
      admin1: {
        username: singh@gmail.com,
        password: manoobilli
      }
    },

   standardUsers: {
     user1: {
       username: user@user.com,
       password: pass
     }
   },

    paypal: {
      sandboxUser: {
         username: Jarrod.Folino@catchoftheday.com.au,
         password: cotdcotd
      },

      mockUser1: {
         username: cotd_1332731257_per@catchoftheday.com.au,
         password: 12345678
      }
    }
}


